clc; clear; close all;

%% ---------- Build element radiation pattern G(theta) using HEX_Gain_Phi0 ----------
% First 3 columns in the Excel file:
%   1: Theta [deg]
%   2: Phi   [deg]
%   3: Abs(Dir) [dBi]

T = readtable('HEX_Gain_Phi0.xlsx');   % File name

theta_all = T{:,1};
phi_all   = T{:,2};
dir_dBi   = T{:,3};

% Fix phi = 0 degrees, and only keep theta = 0~180 degrees
phi0 = 0;
mask = (abs(phi_all - phi0) < 1e-6) & (theta_all >= 0) & (theta_all <= 180);

theta_deg = theta_all(mask);    % 0~180 degrees
G_dBi     = dir_dBi(mask);

% dBi -> linear gain
G_lin = 10.^(G_dBi/10);

% Sort by theta
[theta_deg, idx] = sort(theta_deg);
G_lin            = G_lin(idx);

% Remove repeated theta values to avoid interp1 errors
[theta_deg, ia] = unique(theta_deg);
G_lin = G_lin(ia);

% Element pattern:
% a_rad is the geometric angle from the element to the observation point,
% measured relative to the +y axis, in radians.
% The angle is mapped to theta for table lookup.
% Here theta = |a| is used.
element_gain = @(a_rad) ...
    interp1(theta_deg, G_lin, ...
            abs(rad2deg(a_rad)), ...
            'linear', 0);

%% ---------- Basic parameters ----------
lambda = 0.012;          % Wavelength (m)
d = lambda/2;            % Element spacing (m)
N = 20;                  % Number of elements
Pt = 100;                % Transmit power per element (W)

%% ---------- Array geometry: along the x-axis and symmetric about the origin ----------
idx = (-(N-1)/2 : (N-1)/2);   % -9.5:9.5 (length N)
ant_x = idx * d;              % Element x-coordinates
ant_y = zeros(size(ant_x));   % All y = 0

%% ---------- Observation grid ----------
x_range = -10:0.05:10;        % x range (m)
y_range = 0:0.05:20;          % y range (m)
[X, Y] = meshgrid(x_range, y_range);

%% ---------- Reference: isotropic single-antenna power density ----------
dx1 = X;
dy1 = Y;
r1  = sqrt(dx1.^2 + dy1.^2);
r1(r1 == 0) = eps;            % Avoid division by zero

Pden_iso = Pt ./ (4*pi*r1.^2);    % Isotropic reference, without element pattern

%% ---------- 20-element array power density using complex-amplitude summation ----------
Re = zeros(size(X));
Im = zeros(size(X));

for k = 1:N
    dx = X - ant_x(k);
    dy = Y - ant_y(k);
    r  = sqrt(dx.^2 + dy.^2);
    r(r == 0) = eps;

    % Geometric angle a relative to the +y axis
    a = atan2(dx, dy);   % rad, approximately [-pi/2, pi/2]

    % Element pattern power gain from theta interpolation
    G_elem = element_gain(a);

    % Power density generated by one element in this direction
    Pden_k = G_elem .* Pt ./ (4*pi*r.^2);

    % Field amplitude is proportional to sqrt(power density)
    V_k = sqrt(Pden_k);

    % Propagation phase
    phi_k = 2*pi*r/lambda;

    % Coherent summation
    Re = Re + V_k .* cos(phi_k);
    Im = Im + V_k .* sin(phi_k);
end

Vabs = hypot(Re, Im);            % Magnitude of total field
Pden_array20 = Vabs.^2;          % Array power density

%% ---------- Total array gain in linear scale and dB, relative to N isotropic elements ----------
G = Pden_array20 ./ (N * Pden_iso);
G(~isfinite(G)) = NaN;
GdB = 10*log10(G);

%% ---------- Visualisation: 2D gain distribution in dB ----------
figure;
imagesc(x_range, y_range, GdB);
axis xy; axis equal; box on;
colormap(jet); colorbar;
clim([-20 25]);   % Adjustable display range
title('Total Gain Map of a 20-Element Linear Array');
xlabel('Lateral position, x (m)');
ylabel('Longitudinal position, y (m)');
cb = colorbar;
ylabel(cb, 'Array gain, G (dB)');